# Generated by Django 3.2.6 on 2021-08-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductMedia',
            new_name='ProductImage',
        ),
    ]
