# Generated by Django 3.2.6 on 2021-08-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_category_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
