# Generated by Django 3.2.6 on 2021-08-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_added_by_merchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='added_by_merchant',
            new_name='added_by',
        ),
    ]
