# Generated by Django 3.2.6 on 2021-08-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/merchant'),
        ),
    ]
