# Generated by Django 3.2.6 on 2021-08-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_merchantuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/admin'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='position',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Marketing Officer', 'Marketing Officer'), ('Customer Care', 'Customer Care'), ('Quality Officer', 'Quality Officer')], max_length=255, null=True),
        ),
    ]
