# Generated by Django 3.2.6 on 2021-08-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_added_by_merchant'),
        ('accounts', '0003_auto_20210820_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='merchantuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
        migrations.DeleteModel(
            name='MerchantUser',
        ),
        migrations.DeleteModel(
            name='StaffUser',
        ),
    ]
